# Generated by Django 5.0.3 on 2024-04-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoderH', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
