# Generated by Django 5.0.3 on 2024-04-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoderH', '0003_alumno_avatar_profesor_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profesores'),
        ),
    ]
