# Generated by Django 5.0.3 on 2024-04-21 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoderH', '0007_alter_avatar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='avatar',
        ),
    ]
